apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: tks-coins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - image: us-east1-docker.pkg.dev/tks-gcr-pub/tks-coins/worker:v1.0.1
        imagePullPolicy: IfNotPresent
        name: worker
